name: 'Kiểm thử'
on: 

  workflow_dispatch:
jobs:
  build:
    name: 'Xem quá trình...'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Xem thông báo'
        run: |
          # Rom Rebuild
          export SIZE='8.5'; export NNTV='Viet_Nam'; export URL='https://down.warbler.cc/XiaoMi-Mix-2/MIUI-Xuebao/Paper_MIX2_MIUI12.5-r9.7-%E9%BE%99%E8%85%BE%E8%B1%B9%E5%8F%98.zip'
          chmod -R 777 .github/bin/* >/dev/null
          export PATH="$GITHUB_WORKSPACE/.github/bin:$PATH"
          chmod -R 777 .github/*.sh >/dev/null
          bash .github/Chay.sh
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 0
