name: REBUILD Rom MIUI by chamchamfy & kakathic
on: 
  workflow_dispatch:
    inputs:
      URL:
        description: 'Hãy điền đường dẫn url của link rom để tải xuống'
        required: true
        default: 'https://down.warbler.cc/XiaoMi-Mix-2/MIUI-Xuebao/Paper_MIX2_MIUI12.5-r9.7-%E9%BE%99%E8%85%BE%E8%B1%B9%E5%8F%98.zip'
      SIZE:
        description: 'Kích cỡ phân vùng super'
        required: true
        default: '8.5'
      NNTV:
        description: 'Ngôn ngữ dành riêng cho khu vực'
        required: true
        default: 'Viet_Nam'
        type: choice
        options:
          - Viet_Nam
          - Global
jobs:
  build:
    name: 'Xem quá trình...'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Xem thông báo'
        env:
          URL: ${{ inputs.URL }}
          SIZE: ${{ inputs.SIZE }}
          NNTV: ${{ inputs.NNTV }}
        run: |
          # Rom Rebuild 
          bash .github/Chay.sh
      - uses: actions/upload-artifact@v3
        with:
          name: ZH-UI_${{ env.TENZ }}
          path: .github/lib/Flash_2in1/*
          retention-days: 2
     
